name = "Friends MC"
author = "chengweialan"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c9ac0da061bb3be9f79de2a38a9f6c3fea9d6f05ffdc80365acb96aa8d775245"

[versions]
minecraft = "26.3"
neoforge = "26.3.0.26-beta"
