name = "Friends MC"
author = "chengweialan"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19c9a61495c932de8e5da94063f4661cbc10f55c870e7ffe52d16854eeec71d1"

[versions]
minecraft = "26.3"
neoforge = "26.3.0.26-beta"
