name = "Friends MC"
author = "chengweialan"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99c971f696ef4f1bd2fdcc388c20ab3954e9a7a684c956a6be13e1b348142539"

[versions]
minecraft = "26.3"
neoforge = "26.3.0.26-beta"
